/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as StockRouteImport } from './routes/stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/custom-order': typeof CustomOrderRoute
  '/inspection': typeof InspectionRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/custom-order': typeof CustomOrderRoute
  '/inspection': typeof InspectionRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/custom-order': typeof CustomOrderRoute
  '/inspection': typeof InspectionRoute
  '/stock': typeof StockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/b2b' | '/custom-order' | '/inspection' | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/b2b' | '/custom-order' | '/inspection' | '/stock'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/b2b'
    | '/custom-order'
    | '/inspection'
    | '/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  B2bRoute: typeof B2bRoute
  CustomOrderRoute: typeof CustomOrderRoute
  InspectionRoute: typeof InspectionRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  B2bRoute: B2bRoute,
  CustomOrderRoute: CustomOrderRoute,
  InspectionRoute: InspectionRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
